apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalance-tech
  namespace: default
  labels:
    app: avalance-tech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avalance-tech
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: avalance-tech
    spec:
      containers:
      - name: avalance-tech
        image: dvaio/avalance-tech:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: avalance-secrets
              key: mongodb-uri
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: avalance-secrets
              key: sendgrid-api-key
        - name: EMAIL_FROM
          value: "info@avalance-resources.online"
        - name: ADMIN_EMAIL
          value: "avalancetechpartner@gmail.com"
        resources: {}
      restartPolicy: Always